### ISSUE TITLE
ov7670

### ISSUE THREAD

**Issue by amirjak** [Knowledge91/esp32cam#1]
i want to use this code for another project with ov7670 it's possible ?

![](https://user-images.githubusercontent.com/46311349/56453964-0812bf00-635f-11e9-8124-6c4e974d2ee0.jpg)

**Comment by derdrdirk** [comment]
I don't think so. I am using the [camera driver](https://github.com/espressif/esp32-camera) from espressif, which states that it is compatible with the OV2640 and OV3660 cameras.

**Comment by amirjak** [comment]
Thank you
